export {default as HeaderComp} from './Header/HeaderComp'
export {default as SearchComp} from './Search/SearchComp'
export {default as FormComp} from './Form/FormComp'
export {default as ExternalAuthComp} from './ExternalAuth/ExternalAuth'
export {default as Footer} from './Footer/Footer'