export const GOOGLE_SIGN_IN  = "GOOGLE_SIGN_IN"
export const GOOGLE_SIGN_OUT = "GOOGLE_SIGN_OUT"
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const CREATE_USER = "CREATE_USER"
export const CREATE_SUCESS = "CREATE_SUCESS"
export const CREATE_FAIL = "CREATE_FAIL"